image: node:latest

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
   - node_modules
   - .yarn-cache

before_script:
 - yarn config set cache-folder .yarn-cache
 - yarn install --pure-lockfile

lint:
  script:
   - yarn run lint

test:
  script:
   - yarn run test
